/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp kbd_event.xml -a KbdEvAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KBDEVADAPTOR_H
#define KBDEVADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.esi.kbdev
 */
class KbdevAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.esi.kbdev")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.esi.kbdev\">\n"
"    <signal name=\"key_ev_sig\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"keyname\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"actname\"/>\n"
"    </signal>\n"
"    <method name=\"key_ev_slot\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"keyname\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"actname\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KbdevAdaptor(QObject *parent);
    virtual ~KbdevAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void key_ev_slot(const QString &keyname, const QString &actname);
Q_SIGNALS: // SIGNALS
    void key_ev_sig(const QString &keyname, const QString &actname);
};

#endif
