/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp kbd_event.xml -p KbdEvInterface
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KBDEVINTERFACE_H
#define KBDEVINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.esi.kbdev
 */
class ComEsiKbdevInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.esi.kbdev"; }

public:
    ComEsiKbdevInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ComEsiKbdevInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> key_ev_slot(const QString &keyname, const QString &actname)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(keyname) << QVariant::fromValue(actname);
        return asyncCallWithArgumentList(QStringLiteral("key_ev_slot"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void key_ev_sig(const QString &keyname, const QString &actname);
};

namespace com {
  namespace esi {
    typedef ::ComEsiKbdevInterface kbdev;
  }
}
#endif
